services:
  tarantool:
    image: tarantool/tarantool
    container_name: tarantool
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool:/opt/tarantool
    command: >
      tarantool /opt/tarantool/init.lua
    restart: unless-stopped

  vk-mid-sprint:
    image: vk-mid-sprint:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: on-failure
    ports:
      - "8080:8080"

